variables:
  GIT_SUBMODULE_STRATEGY: recursive

test-julia:
  interruptible: true
  image: julia:1.6
  variables:
    # Store packages locally to allow caching.
    JULIA_DEPOT_PATH: ${CI_PROJECT_DIR}/.julia
    JULIA_PROJECT: '@.'
  script:
    - julia -e 'using InteractiveUtils; versioninfo()'
    - julia -e 'using Pkg; Pkg.instantiate()'
    - julia test/runtests.jl
  cache:
    key: $CI_JOB_NAME
    paths:
      - .julia/packages
      - .julia/compiled
      - .julia/registries
