#!/bin/bash
#SBATCH -J dense-par
#SBATCH -o %x-%j.out
#SBATCH -e %x-%j.err
#
#SBATCH -n 15
#SBATCH -c 4
#
#SBATCH --time=00-1:00:00
#SBATCH --partition=short
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=jschulze@mpi-magdeburg.mpg.de

set -eu

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK:-1}
export MKL_ENABLE_INSTRUCTIONS=AVX2
export JULIA_PROJECT=@.

export MY_NCOARSE=1
export MY_NFINE=10
export MY_OCOARSE=1
export MY_OFINE=1

module load apps/julia/1.6

julia solve.jl
